brain_two/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoListView,
    TodoDetailView,

)

urlpatterns = [
    path("", TodoListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoDetailView.as_view(), name="todo_list_detail"),


]

todos/models.py
from django.db import models

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(auto_now=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from todos.models import TodoList
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

# Create your views here.


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Todo Lists</title>
</head>

<body>
    <main>
        <div>
            <h1>Reminders</h1>
            <h2>Tasks</h2>
              <table>
                <thead>
                    <tr>
                        <td>Task</td>
                        <td>Due Date</td>
                    </tr>
                    <tbody>
                        {% for item in todolist.items.all %}
                        <tr>
                            <td>{{ item.task }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </thead>
              </table>
        </div>
    </main>
    
</body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>

<html lang="en">
<head>
    <title>Todo Lists</title>
</head>

<body>
    <header>

    </header>
    <main>
        <div>
            <h1>My Lists</h1>
            <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of items</th>
                </tr>
            </thead>
                <tbody>
                    {% for todo in todolist_list %}
                    <tr>
                        <a href="{% url "todo_list_detail"
                        item.pk %}">
                          <td>{{ todo.name }}</td>
                        </a>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </main>

</body>
</html>